spring:
  application:
    name: kegiatan-service
  lifecycle:
    timeout-per-shutdown-phase: 15s
  r2dbc:
    username: user
    password: password
    url: r2dbc:postgresql://localhost:5432/kertaskerja_kegiatan
    pool:
      max-size: 10
      initial-size: 5
      max-create-connection-time: 2s
  flyway:
    user: ${spring.r2dbc.username}
    password: ${spring.r2dbc.password}
    url: jdbc:postgresql://localhost:5432/kertaskerja_kegiatan


server:
  port: 9005
  netty:
    connection-timeout: 2s
    idle-timeout: 15s
  shutdown: graceful


kertaskerja:
  status: KEGIATAN SERVICE IS UP
  client:
    program-service-uri: http://localhost:9004